import { EstateInfo } from '../interfaces';

export const estatesInfo: EstateInfo[]  = [
    {   
        ID: 101,
        name: 'Lomas Country Club',
        slug: 'lomas-country-club',
        address: 'Porton de las flores 27, Cascatta II, Huixquilucan',
        costs: 6500000,
        state: 'venta',
        type: 'departamentos',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 1,
        rooms: 4,
        baths: 3,
        parking: 4,
        m2live: 150,
        m2total: 230,
        description: 'Permuta o vende el propietario por departamento en Acapulco, Cancún o Mérida.',
        others: [
           'Vestidor',
           'Sala comedor',
           'Cocina equipada',
           'Cuarto de servicio con elevador independiente',
           'Cuarto de lavado muy amplió', 
        ],
        amenities: [
            'Recepción',
            'Salón usos múltiples',
            'Gimnasio',
            'Salon de juegos',
            'Estacionamiento amplio de visitas'
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },


    {   
        ID: 102,
        name: 'Encino',
        slug: 'encino',
        address: 'Calle Encino 110 Santa Monica, Valle de los Pinos.',
        costs: 4500000,
        state: 'venta',
        type: 'casas',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 4,
        rooms: 5,
        baths: 2,
        parking: 2,
        m2live: 360,
        m2total: 140,
        description: 'Por precio condiciones la mejor opción, un baño y medio.',
        others: [
           'Sala comedor',
           'Cocina equipada',
           'Despacho amplió',
           'Sala de TV',
           'Cuarto de lavado',
           'Terraza 70 mts como roof garden',
           'Calle cerrada solo transito local'
        ],
        amenities: [
            'Seguridad',
            'A 2 calles del periferico norte a 5 minutos de Plaza Satelite',
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 103,
        name: 'Lomas de Chapultepec',
        slug: 'lomas-de-chapultepec',
        address: 'Av. De las Palmas 800 Torre Palmas, Polanco.',
        costs: 20000000,
        state: 'venta',
        type: 'departamentos',
        town: 'CDMX',
        townSlug: 'cdmx',
        levels: 1,
        rooms: 3,
        baths: 3,
        parking: 2,
        m2live: 290,
        m2total: 230,
        description: 'A 4 minutos de Polanco, en el octavo piso.',
        others: [
            'Sala',
            'Comedor',
            'Cocina equipada',
        ],
        amenities: [
            'Alberca',
            'Salón de juegos',
            '4 restaurantes en piso 32',
            'Gimnasio',
            'Sauna',
            'Vapor',
            'Barbería y estética damas',
            'Tienda interna, mini super',
            'Jardín',
            'Ludoteca',
            'Blibioteca',
            'Inmueble construido hace 30 años.',
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },

    {   
        ID: 104,
        name: 'Lopez Mateos',
        slug: 'lopez-mateos',
        address: 'Av. Lopez Mateos #36 Col. Francisco Villada, Tlalnepantla',
        costs: 9000000,
        state: 'venta',
        type: 'terrenos',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 4,
        rooms: 15,
        baths: 8,
        parking: 8,
        m2live: 800,
        m2total: 310,
        description: 'A 1 minuto del palacio municipal de Atizapán de Zaragoza. Ideal para escuela chica, oficinas, restaurante, clínica, ferretería y otros.',
        others: [
           'Espacios múltiples',
        ],
        amenities: [
            '',
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 105,
        name: 'Club de Golf Bellavista',
        slug: 'club-de-golf-bellavista',
        address: 'Calle Riachuelo, club de Golf Bellavista, Atizapán de Zaragoza.',
        costs: 17500000,
        state: 'venta',
        type: 'casas',
        town: 'Edo. de México.',
        townSlug: 'mexico',
        levels: 2,
        rooms: 3,
        baths: 4,
        parking: 8,
        m2live: 620,
        m2total: 500,
        description: 'A 5 minutos de mundo E',
        others: [
           'Sala',
           'Comedor',
           'Cocina equipada',
           'Jardín delantero y trasero',
        
        ],
        amenities: [
            'Fraccionamiento con exclusividad y seguridad, mantenimiento mensual de $5000.00.',
        
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 106,
        name: 'Cumbres Norte',
        slug: 'cumbres-norte-venta',
        address: 'Cumbres Norte, Cuatitlan Izcalli',
        costs: 2850000,
        state: 'venta',
        type: 'departamentos',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 1,
        rooms: 3,
        baths: 2,
        parking: 2,
        m2live: 148,
        m2total: 148,
        description: 'A 5 minutos de Plaza Satélite sin tráfico, en el septimo piso',
        others: [
           'Sala comedor',
           'Cocina integral',
           'Estacionamiento techado', 
        ],
        amenities: [
            'Salón usos múltiples',
            'Áreas verdes 1000 mts',
            'Mantenimiento $1400 mensuales',
            'Estacionamiento para visitas'
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 107,
        name: 'Club de Golf Bellavista',
        slug: 'club-de-golf-bellavista-tlalne',
        address: 'Calle Arroyo, Tlalnepantla',
        costs: 3200000,
        state: 'venta',
        type: 'casas',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 2,
        rooms: 5,
        baths: 5,
        parking: 2,
        m2live: 200,
        m2total: 400,
        description: 'Casa de diseño hecha por arquitectos Aragones, 4 baños y uno de visitas',
        others: [
           'Recámara principal con vestidor y jacuzzi',
           'Despacho con terraza',
           '2 salas',
           'Chimenea en la sala',
           'Plafones con vigas de madera', 
           'Terraza techada',
           'Family room',
           'Antecomedor',
           'Cocina de cuarzo',
           'Patio de servicio',
           'Cisterna 10000 litros',
           '2 desniveles',

        ],
        amenities: [
            '',
           
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 103,
        name: 'Lomas de Chapultepec',
        slug: 'lomas-de-chapultepec-renta',
        address: 'Av. de las Palmas 800 Torre Palmas, Polanco.',
        costs: 80000,
        state: 'renta',
        type: 'departamentos',
        town: 'CDMX',
        townSlug: 'cdmx',
        levels: 1,
        rooms: 3,
        baths: 3,
        parking: 2,
        m2live: 290,
        m2total: 230,
        description: 'A 4 minutos de Polanco, en octavo piso.',
        others: [
           'Sala',
           'Comedor',
           'Cocina equipada',
    
        ],
        amenities: [
            'Alberca',
            'Salón de juegos',
            '4 restaurantes en piso 32',
            'Gimnasio',
            'Sauna',
            'Vapor',
            'Barbería y estética damas',
            'Tienda interna, mini super',
            'Jardín',
            'Ludoteca',
            'Biblioteca',
            'Inmueble construido hace 30 años'
        
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 104,
        name: 'Lopez Mateos',
        slug: 'lopez-mateos-renta',
        address: 'Av. Lopez Mateos #36 Col. Francisco Villada, Tlalnepantla',
        costs: 70000,
        state: 'renta',
        type: 'terrenos',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 4,
        rooms: 15,
        baths: 8,
        parking: 8,
        m2live: 800,
        m2total: 310,
        description: 'A un minuto del palacio municipal de Atizapán. Ideal para escuela chica, oficinas, restaurante, clínica, ferretería y otros.',
        others: [
           'Espacios múltiples',
            
        ],
        amenities: [
            '',
            
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
    {   
        ID: 106,
        name: 'Cumbres Norte',
        slug: 'cumbres-norte-renta',
        address: 'Cumbres Norte, Cuatitlan Izcalli',
        costs: 16000,
        state: 'renta',
        type: 'departamentos',
        town: 'Edo. de México',
        townSlug: 'mexico',
        levels: 1,
        rooms: 3,
        baths: 2,
        parking: 2,
        m2live: 148,
        m2total: 148,
        description: 'A 5 minutos de Plaza Satélite sin tráfico, en el septimo piso, renta amueblado el costo es de $200000',
        others: [
           'Sala comedor',
           'Cocina integral',
           'Estacionamiento techado',

        ],
        amenities: [
            'Salón usos mùltiples',
            'Áreas vedes 1000 mts',
            'Mantenimiento $1400 mensuales',
            'Estacionamiento para visitas'
        ],
        images: [
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/40db7373-3167-4c06-865b-e4c18631a34d.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/dcc35fed-41e2-4d5d-aff8-205bee1b1f19.jpg?im_w=1200',
        ],
    },
];